---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - externalsecret.yml
  - ingress.yml
  - pvc.yml
  - service.yml

configMapGenerator:
  - name: listmonk-config
    files:
      - config.toml
  - name: listmonk-envs
    envs:
      - configs.env

namespace: listmonk
